#!/usr/bin/env bash
# Bash script that displays:content of the current directory in list format where, only the part of the name after the first dash is displayed
# Use for loop

list=$(ls)

for i in $list; do

  echo "$i" | cut -d '-' -f2

done 
